//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int purchaseId { get; set; }
        public Nullable<int> originCountry { get; set; }
        public Nullable<int> purchaseCountry { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> prodId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> subcategoryId { get; set; }
    
        public virtual category category { get; set; }
        public virtual product product { get; set; }
        public virtual subcategory subcategory { get; set; }
    }
}
